Repository qonto/prometheus-rds-exporter, pull requests merged in 2023-11, with the labels that each got.

#36 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#38 chore(metrics): Export RDS Certificate Authority attributes
  README.md
  internal/app/exporter/exporter.go
  internal/app/rds/rds.go
  internal/app/rds/rds_test.go
Labels: enhancement

#40 Add instance age metric
  README.md
  docs/add-metric.md
  internal/app/exporter/exporter.go
  internal/app/rds/rds.go
  internal/app/rds/rds_test.go
Labels: enhancement

#34 Rename metrics without units
  README.md
  internal/app/cloudwatch/usage.go
  internal/app/cloudwatch/usage_test.go
  internal/app/exporter/exporter.go
  internal/app/rds/rds.go
  internal/app/rds/rds_test.go
  internal/app/servicequotas/servicequotas.go
  internal/app/servicequotas/servicequotas_test.go
  internal/app/unit/converter.go
  internal/app/unit/converter_test.go
Labels: enhancement

#42 Avoid crashing when CA information is not available
  internal/app/exporter/exporter.go
  internal/app/rds/rds.go
  internal/app/rds/rds_test.go
Labels: bug

#43 Readme improvements
  README.md
Labels: documentation

#45 Add Golang dashboard
  scripts/prometheus/configuration/grafana/entrypoint.sh
Labels: enhancement

#48 Upgrade Grafana & Prometheus
  scripts/prometheus/docker-compose.yml
Labels: enhancement

#47 Enable dependabot
  .github/dependabot.yml
Labels: enhancement
